# Generated by Django 3.1.5 on 2021-01-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift_availibilty',
            new_name='shift_availibility',
        ),
    ]
